CREATE TABLE [Fee].[Item]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newid()), 
    [Name] NVARCHAR(100) NOT NULL, 
    [ItemTypeId] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [FK_Item_ItemType] FOREIGN KEY ([ItemTypeId]) REFERENCES [Fee].[ItemType]([Id])
)
